### ISSUE TITLE
Scroll to Top button 

### ISSUE THREAD

**Issue by Hariom8799** [ShehrozIrfan/portfolio#10]
There would be an Scroll to Top button in bottom right side of the window ,when someone click on that the page will be on top

**Comment by Hariom8799** [comment]
pls assign me this issue

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Assigned.

**Comment by Hariom8799** [comment]
pls add the hacktober feast label 😁😁

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Pardon me.
I mistakenly assign this to you. Actually, it's not for Hacktoberfest.
Thanks.
